/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/example/advance/communication': RouteRecordInfo<'/example/advance/communication', '/example/advance/communication', Record<never, never>, Record<never, never>>,
    '/example/advance/promise': RouteRecordInfo<'/example/advance/promise', '/example/advance/promise', Record<never, never>, Record<never, never>>,
    '/example/base/': RouteRecordInfo<'/example/base/', '/example/base', Record<never, never>, Record<never, never>>,
    '/example/base/compatible-native-attributes': RouteRecordInfo<'/example/base/compatible-native-attributes', '/example/base/compatible-native-attributes', Record<never, never>, Record<never, never>>,
    '/example/base/components/Content': RouteRecordInfo<'/example/base/components/Content', '/example/base/components/Content', Record<never, never>, Record<never, never>>,
    '/example/base/confirm': RouteRecordInfo<'/example/base/confirm', '/example/base/confirm', Record<never, never>, Record<never, never>>,
  }
}
